//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ingredient()
        {
            this.product_ingresients = new HashSet<product_ingresients>();
        }
    
        public int id { get; set; }
        [DisplayName("Tên thành phần")]
        public string name { get; set; }
        [DisplayName("Mô tả")]
        public string description { get; set; }
        [DisplayName("Đơn vị")]
        public string unit { get; set; }
        public bool disable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_ingresients> product_ingresients { get; set; }
    }
}
