//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrderSystemEntities2 : DbContext
    {
        public OrderSystemEntities2()
            : base("name=OrderSystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<feed_back> feed_back { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<menu_detail> menu_detail { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<otp_table> otp_table { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_ingresients> product_ingresients { get; set; }
        public virtual DbSet<service_time> service_time { get; set; }
        public virtual DbSet<time_menu> time_menu { get; set; }
        public virtual DbSet<topup_card> topup_card { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int sp_update_balance(Nullable<int> transID, Nullable<int> userID, Nullable<double> amount)
        {
            var transIDParameter = transID.HasValue ?
                new ObjectParameter("transID", transID) :
                new ObjectParameter("transID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_balance", transIDParameter, userIDParameter, amountParameter);
        }
    }
}
