//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrderSystemEntities1 : DbContext
    {
        public OrderSystemEntities1()
            : base("name=OrderSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<balance> balances { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<index_table> index_table { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<menu_detail> menu_detail { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<otp_table> otp_table { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_ingresients> product_ingresients { get; set; }
        public virtual DbSet<service_time> service_time { get; set; }
        public virtual DbSet<time_menu> time_menu { get; set; }
        public virtual DbSet<topup_card> topup_card { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int sp_add_record_balance(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_record_balance", userIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_check_login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_check_login", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_update_balance(Nullable<int> userID, Nullable<double> amount)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_balance", userIDParameter, amountParameter);
        }
    }
}
