//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class otp_table
    {
        public int uId { get; set; }
        public int otp { get; set; }
        public System.DateTime create_time { get; set; }
    
        public virtual user user { get; set; }
    }
}
