//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_ingresients
    {
        public int productID { get; set; }
        public int ingID { get; set; }
        public int amount { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual product product { get; set; }
    }
}
