//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class topup_card
    {
        public string serial_number { get; set; }
        public string code { get; set; }
        public int value { get; set; }
        public System.DateTime create_time { get; set; }
        public int creator { get; set; }
        public Nullable<int> used_by { get; set; }
        public Nullable<System.DateTime> used_time { get; set; }
    
        public virtual user user { get; set; }
        public int amount { get; set; }
    }
}
